force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/DOJ__c.field-meta.xml
<CustomField>
    <fullName>DOJ__c</fullName>
    <label>DOJ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>absconded</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Training__c.Status__c</field>
            <operation>contains</operation>
            <value>Started, In Progress</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRAIN-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Cource_Name__c.field-meta.xml
<CustomField>
    <fullName>Cource_Name__c</fullName>
    <label>Cource Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StudentDOJUpdateTest.cls
@isTest
public class StudentDOJUpdateTest {

    @isTest
    public static void adjustDOJTest(){
         Profile p = [Select Id from Profile where Name = 'Customer Profile' limit 1];
        Date tday = System.today();
        User u = new User(firstName='Test',LastName='User',Email='TestUser@gmail.com',EmailEncodingKey = 'ISO-8859-1', 
                          Alias ='tesus', 
                          TimeZoneSidKey = 'America/Los_Angeles', 
                          LocaleSidKey = 'en_US', 
                          LanguageLocaleKey = 'en_US',Username = 'TestUser'+tday.day()+tday.month()+tday.year()+'@gmail.com',ProfileId = p.Id);
        insert u;
        System.runAs(u){
        Training__c train = new Training__c(Cource_Name__c = 'Test',Status__c='Started',Start_Date__c = tday);
        
        insert train;
        
        Student__c st = new Student__c(Name='Test Student',DOJ__c = tday,Status__c='Active',Training__c = train.Id);
        insert st;
        
        Test.startTest();
        update train;
        Test.stopTest();
        
        Student__c st1 = [Select Id,DOJ__c from Student__c where Id =: st.id];
        
        System.assertEquals(tday.addDays(1), st1.DOJ__c);
        }
    }
}