force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/DOJ__c.field-meta.xml
<CustomField>
    <fullName>DOJ__c</fullName>
    <label>DOJ</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Training__c.field-meta.xml
<CustomField>
    <fullName>Training__c</fullName>
    <label>Training</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Training__c.Status__c</field>
            <operation>contains</operation>
            <value>Started, In Progress</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Training__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRAIN-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/StudentDOJUpdate.cls
public class StudentDOJUpdate {

    @InvocableMethod(label = 'AdjustDOJ')
    public static void adjustDOJ(List<Id> trainingIds){
        
        List<Student__c> students = new List<Student__c>([Select Id,DOJ__c from Student__c where Training__c IN : trainingIds]);
        
        for(Student__c st : students){
            st.DOJ__c = st.DOJ__c.addDays(1);
        }
        
        update students;
    }
}