force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRAIN-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Cource_Name__c.field-meta.xml
<CustomField>
    <fullName>Cource_Name__c</fullName>
    <label>Cource Name</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrainingBatchTest.cls
@isTest
public class TrainingBatchTest {
    
    
    @isTest
    static void dateTest(){
        List<Training__c> trains = new List<Training__c>();
        for(Integer i=1;i<=200;i++){
            trains.add(new Training__c(Cource_Name__c = 'Test'+i,Status__c='Started',Start_Date__c = System.today()));
        }
        insert trains;
        
        Test.startTest();
        TrainingBatch tb = new TrainingBatch('Started');
        Database.executeBatch(tb, 200);
        Test.stopTest();
        
        List<Training__c> trainsUpdated = [Select End_Date__c from Training__c];
        
        System.assert(trainsUpdated[0].End_Date__c != null);
    }
}