force-app/main/default/objects/Training__c/Training__c.object-meta.xml
<CustomObject>
    <label>Training</label>
    <nameField>
        <displayFormat>TRAIN-{0000}</displayFormat>
        <label>Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Training__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrainingBatch.cls
public class TrainingBatch implements Database.Batchable<sObject>{
    
    public String status;
    public TrainingBatch(String status){
        this.status = status;
    }
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        String query = 'SELECT Id, End_Date__c, Status__c FROM Training__c where Status__c =: status';
        
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc,List<Training__c> trainings){
        for(Training__c t : trainings){
            t.End_Date__c = t.End_Date__c == null ? System.today() : t.End_Date__c.addDays(1);
        }
        
        update trainings;
    }
    
    public void finish(Database.BatchableContext bc){
        
    }
}